import express, { type Request, type Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { authRoutes } from './modules/auth/index.js';
import { categoryRoutes } from './modules/categories/index.js';
import { transactionRoutes } from './modules/transactions/index.js';
import { budgetRoutes } from './modules/budgets/index.js';
import { dashboardRoutes } from './modules/dashboard/index.js';
import { errorHandler } from './middleware/errorHandler.js';
import { authenticate } from './middleware/authenticate.js';
dotenv.config();
const app = express();
const PORT = process.env.PORT ?? 4000;
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN ?? 'http://localhost:5173';
app.use(cors({ origin: CLIENT_ORIGIN }));
app.use(express.json());
app.get('/health', (_req: Request, res: Response) => { res.status(200).json({ status: 'ok', timestamp: new Date().toISOString() }); });
app.use('/api/auth', authRoutes);
app.use('/api/categories', categoryRoutes);
app.use('/api/transactions', transactionRoutes);
app.use('/api/budgets', budgetRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.get('/api/me', authenticate, (req: Request, res: Response) => { res.status(200).json({ userId: req.userId }); });
app.use(errorHandler);
app.listen(PORT, () => { console.log('BudgetFlow API running at http://localhost:' + PORT); });
